### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by KatharineME** [KwatME/kraft#63]
I installed kraft by cloning it and running `pip install .`

When I called `kraft.get_geo_gse()` the GEO download worked but there was an error later because the function was searching for 
`/Users/kate/miniconda3/lib/python3.8/site-packages/kraft/data/hgnc_complete_set.txt.gz'`which wasn't there because the `data/` folder wasn't copied to there from the `kraft` repository.

So basically, the setup.py function should also copy the `data/` folder to `site-packages/kraft/`.

**Comment by KwatME** [comment]
This is because you need to use GitLFS to get the larger files, which do not come automatically as other files do.
