### ISSUE TITLE
kraft.geo.get_gse()

### ISSUE THREAD

**Issue by KatharineME** [KwatME/kraft#64]
1) `map_cg_to_gene()` in `name_biology.py` is expecting different file formats for the files in `data/`. For example it is expecting `HumanMethylation450_15017482_v1-2.csv.gz` to be a `.csv` file. You can see this error if you run `kraft.geo.get_gse()` 

2) Also, I'm unable to unzip or decompress the `infinitum-methylationepic-v-1-0-b5-manifest-file-csv.zip` file.

**Comment by KwatME** [comment]
That file may be empty. Next time upload the exact error please. This is because I use GitLFS to carry the file. Without using GitLFS, this file is just a pointer (thus empty).
